export const BACKEND_URL = `http://192.168.1.14:8000`;

export const API_ENDPOINTS = {
    profilesCreateProfile: `/profiles/create_profiles/`,
    profilesCheckProfileMailId: `/profiles/check_mail_id/`,
    profilesDeleteProfile: `/profiles/delete_profile/`,
    profilesGetHomeData: `/profiles/get_home_data/`,
    profilesGetHomeData2: `/profiles/get_home_data2/`,
    profilesGetNewData: `/profiles/get_new_data/`,
    profilesGetRecentlyViewedData: `/profiles/get_recently_viewed_data/`,
    profilesGetLikelyData: `/profiles/get_likely_data/`,
    profilesGetMatchesData: `/profiles/get_matches_data/`,
    profilesFetchRequestDetails: `/profiles/fetch_request_details/`,
    profilesGetNotificationsData: `/profiles/get_notifications_data/`,
    profilesMakeAMatch: `/profiles/make_a_match/`,
    profilesSendContactRequest: `/profiles/send_contact_request/`,
    profilesSendRequestToAgent: `/profiles/send_request_to_agent/`,
    profilesSendMatchingRequestToAgent: `/profiles/send_matching_request_to_agent/`,
    profilesGetCurrentUserDetails: `/profiles/get_current_user_details/`,
    profilesGetUserDetails: `/profiles/get_user_details/`,
    profilesPartialUpdateUserProfile: `/profiles/partial_update_user_profile/`,
    profilesUploadProfilePicture: `/profiles/upload_profile_picture/`,
    profilesUploadMultipleImages: `/profiles/upload_multiple_images/`,
    profilesDeleteAllImages: `/profiles/delete_all_images/`,
    profilesSayHello: `/profiles/say_hello/`,

    agentsCreateAgent: `/agents/create_agents/`,
    agentsPartialUpdateAgentProfile: `/agents/partial_update_agent_profile/`,
    agentsCheckAgentMailId: `/agents/check_mail_id/`,
    agentsDeleteAgent: `/agents/delete_agent/`,
    agentsGetAgentDetails: `/agents/get_agent_details/`,
    agentsGetAgentCurrentDetails: `/agents/get_agent_current_details/`,
    agentsGetAllAgents: `/agents/get_all_agents/`,
    agentsGetAllProfiles: `/agents/get_all_profiles/`,
    agentsGetMatchingRequests: `/agents/get_matching_requests/`,
    agentsGetProfilesUploadedByAgent: `/agents/get_profiles_uploaded_by_agent/`,
    agentsAcceptAssignRequest: `/agents/accept_assign_request/`,
    agentsRejectAssignRequest: `/agents/reject_assign_request/`,
    agentsGetAcceptedProfiles: `/agents/get_accepted_profiles/`,

    checkPhoneNumber: `/profiles/check_phone_number_exists/`,
    getCategory: `/profiles/check_uid_origin/`,
    checkAAdharNumber: `/profiles/check_aadhar_number/`,
}